spring:
  application:
    name: catcher  # 애플리케이션 이름
  datasource:
    url: ${DB_URL}  # 데이터베이스 URL
    username: ${DB_USERNAME}  # 데이터베이스 사용자 이름
    password: ${DB_PASSWORD}  # 데이터베이스 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 드라이버 클래스 이름
  jpa:
    hibernate:
      ddl-auto: update  # 데이터베이스 스키마 자동 업데이트
    show-sql: true  # SQL 쿼리 출력 여부
  cache:
    type: redis  # 캐시 유형을 Redis로 설정
    redis:
      time-to-live: 600000  # Redis 캐시의 TTL 설정 (600초)
      host: redis  # Docker Compose의 Redis 서비스 호스트
      port: 6379
      lettuce:
        pool:
          max-active: 5  # 최대 활성 연결 수
          max-idle: 5    # 최대 유휴 연결 수
          min-idle: 2    # 최소 유휴 연결 수
server:
  port: 8081  # 애플리케이션 포트
