spring:
  application:
    name: catcher  # 애플리케이션 이름
  datasource:
    url: ${DB_URL}  # 데이터베이스 URL
    username: ${DB_USERNAME}  # 데이터베이스 사용자 이름
    password: ${DB_PASSWORD}  # 데이터베이스 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 드라이버 클래스 이름
  jpa:
    hibernate:
      ddl-auto: update  # 데이터베이스 스키마 자동 업데이트
    show-sql: true  # SQL 쿼리 출력 여부
  redis:
    host: redis  # Docker Compose의 Redis 서비스 호스트
    port: 6379
server:
  port: 8081  # 애플리케이션 포트
