spring:
  application:
    name: catcher  # ??? catcher? ??? ??? ??
  datasource:
    url: ${DB_URL}  # ?? ??? ?????? URL? ??
    username: ${DB_USERNAME}  # ?? ??? ?????? ????? ??
    password: ${DB_PASSWORD}  # ?? ??? ?????? ????? ??
  jpa:
    hibernate:
      ddl-auto: update  # ?????? ???? ????
    show-sql: true  # ?? ??? ??

server:
  port: ${SERVER_PORT:8081}  # ?? ?? ??? ?? ??? ??, ???? 8081
